{% set month_ref = get_month_ref() %}

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA

FROM {{ ref('vw_efic_op_al_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA
FROM {{ ref('vw_efic_op_ap_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA 
FROM {{ ref('vw_efic_op_go_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA
FROM {{ ref('vw_efic_op_ma_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA
FROM {{ ref('vw_efic_op_pa_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA
FROM {{ ref('vw_efic_op_pi_2025_revisao') }}

UNION ALL

SELECT
EMPRESA,REGIONAL_PRX,POLO_PRX,PROCESSO,SERV_CAMPO,FONECEDOR,EQUIPE,OS_OPER,OS,OSTIPO_ID,OSSUBTIPO_ID,TIPO_CONCLUSAO,TIPO,CH_UPS,VALOR_UPS,COMPETENCIA,DATA_CONCLUSAO,DIAS,TURNOS,OS_OPER_ORIGEM,PREFIXO_ORIGEM,TIPO_ORIGEM,TIPO_CONCLUSAO_ORIGEM,CODIGO_MEDIDA,STATUS_PRAZO,REINCIDENTE_90_DIAS,N_REINC,FLAG_RET,FLAG_PRAZO,FLAG_IMPRODUTIVA,FLAG_IMPROCEDENCIA,FLAG_REINCIDENCIA,DATA_DADOS,FLAG_TOTAL,CATEGORIA
FROM {{ ref('vw_efic_op_rs_2025_revisao') }}

{% if is_incremental() %}
    -- Delete existing rows for the same month before inserting
    {% set delete_sql %}
        DELETE FROM {{ this }}
        WHERE TO_DATE(COMPETENCIA,'YYYYMM') = TO_DATE({{ month_ref }}, 'YYYYMM')
    {% endset %}

    {% do run_query(delete_sql) %}
{% endif %}