SELECT 

TT.EMPRESA,	
TT.REGIONAL_PRX,
TT.POLO_PRX,	
TT.TIPO_EQP,	
TT.PROCESSO,
TT.EQUIPE,	
TT.COMPETENCIA,
TT.QTD_TOTAL,	
NP.QTD_DENTRO,	
(NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100 PERC,
CASE 
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 100 THEN 'A'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 98  THEN 'B'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 96  THEN 'C'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100<  96  THEN 'D'
END  CLASSE_MEPE_PRAZO,
CASE 
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 100 THEN '100'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 98  THEN '70'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100>= 96  THEN '30'
WHEN (NVL(NP.QTD_DENTRO,0)/TT.QTD_TOTAL)*100<  96  THEN '0'
END  MEPE_PRAZO	

FROM 

(SELECT 
A.EMPRESA,	
A.P_REGIONAL REGIONAL_PRX	,
A.P_POLO POLO_PRX,	
A.TIPO_EQP,	
A.P_PROCESSO PROCESSO	,
A.EQUIPE,	
A.COMPETENCIA,
COUNT(A.OS_OPER) QTD_TOTAL	

 FROM {{ ref('serv_exec_detalhado2') }} A
 WHERE A.OSTIPO_ID NOT IN ('IS','NR','MT','CT')
 AND TO_DATE(A.COMPETENCIA, 'YYYYMM') = TO_DATE({{ get_month_ref() }},'YYYYMM')
 AND EMPRESA = 'EQTL_RS'
 


 GROUP BY 
 A.EMPRESA,
A.P_REGIONAL,
A.P_POLO,	
A.TIPO_EQP,	
A.P_PROCESSO,
A.EQUIPE,	
A.COMPETENCIA)	TT

LEFT JOIN 
          (SELECT 
A.EMPRESA,	
A.P_REGIONAL REGIONAL_PRX	,
A.P_POLO POLO_PRX,	
A.TIPO_EQP,	
A.P_PROCESSO PROCESSO	,
A.EQUIPE,	
A.COMPETENCIA,
COUNT(A.OS_OPER) QTD_DENTRO	

 FROM {{ ref('serv_exec_detalhado2') }} A
 WHERE A.OSTIPO_ID NOT IN ('IS','NR','MT','CT')
 AND TO_DATE(A.COMPETENCIA, 'YYYYMM') = TO_DATE({{ get_month_ref() }},'YYYYMM')
 AND EMPRESA = 'EQTL_RS'
 AND A.DATA_CONCLUSAO <= A.DATA_LIMITE 

 GROUP BY 
 A.EMPRESA,
A.P_REGIONAL,
A.P_POLO,	
A.TIPO_EQP,	
A.P_PROCESSO,
A.EQUIPE,	
A.COMPETENCIA) NP ON NP.EMPRESA =  TT.EMPRESA
                                  AND NP.EQUIPE = TT.EQUIPE
                                  AND NP.COMPETENCIA =TT.COMPETENCIA