SELECT
	TT.EMPRESA,
	TT.REGIONAL_PRX,
	TT.POLO_PRX,
	TT.TIPO_EQP,
	TT.PROCESSO,
	TT.EQUIPE,
	TT.COMPETENCIA,
	TT.QTD_TOTAL,
	NP.QTD_DENTRO,
	(NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 PERC,
	CASE
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 100 THEN 'A'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 98 THEN 'B'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 96 THEN 'C'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100< 96 THEN 'D'
	END CLASSE_MEPE_PRAZO,
	CASE
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 100 THEN '100'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 98 THEN '70'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100 >= 96 THEN '30'
		WHEN (NVL(NP.QTD_DENTRO, 0)/ TT.QTD_TOTAL)* 100< 96 THEN '0'
	END MEPE_PRAZO
FROM
	(
	SELECT
		t.empresa,
		t.regional_prx,
		t.polo_prx,
		t.tipo_eqp,
		t.processo,
		t.equipe,
		t.competencia,
		sum(t.qtd_total)qtd_total
	FROM
		(
		SELECT
			B.DISTRIBUIDORA EMPRESA,
			B.REGIONAL REGIONAL_PRX ,
			B.POLO POLO_PRX,
			B.TIPO_EQP TIPO_EQP,
			B.PROCESSO PROCESSO ,
			REPLACE(A.EQUIPE_EXECUCAO, 'MA_', '') EQUIPE,
			A.MES_COMPETENCIA COMPETENCIA,
			COUNT(A.NOTA) QTD_TOTAL
		FROM
			{{ ref('prazo_sap_stc_ma') }} A
		LEFT JOIN {{ ref('vw_gp_gstc_equipes_sem_duplicatas') }} B ON
			B.DISTRIBUIDORA = A.EMPRESA
			AND B.PREFIXO = REPLACE(A.EQUIPE_EXECUCAO, 'MA_', '')
			--LEFT JOIN OWENGCMR.EQUIPES_STC_DE_PARA C ON C.EMPRESA = A.EMPRESA AND C.NOVO=REPLACE(A.EQUIPE_EXECUCAO, 'MA_', '')
		WHERE
			TO_DATE(A.MES_COMPETENCIA, 'YYYYMM') = TO_DATE({{ get_month_ref() }},'YYYYMM')
			AND A.STATUS_CCS NOT IN ('CANC')
			AND A.CODIFICACAO NOT IN ('CMRE', 'LNGA', 'PLPT', 'REDF')
			AND A.GRUPO_CODES NOT IN ('ACESMNGD', 'DSPEDEMP', 'LIGEATBT', 'LIGNOVAT', 'RELIGAAT', 'RELIGARI', 'RELIGARM', 'DSBTREMO', 'DSDEFFAT', 'SATEMPAT', 'INSPCOME', 'LIGEMUC', 'LIGNOVRE', 'LNMICRGD')
			AND A.TIPO_NOTA NOT IN ('IS')
			AND A.GRUPO_MEDIDA NOT IN ('AGCLPMM', 'AGPGCASP', 'AGPGCPAR', 'ANACAPAS', 'ANALIMED', 'CORRECRO', 'DISPONPI', 'ENVBOLE', 'EXECONGD', 'EXEOBRRO', 'GERABAPO',
'INFOEXPA', 'INFOGERE', 'INSPOBRD', 'INTELEDE', 'OBRAINTE', 'ORCAPTAV', 'PENDOBRA', 'PENSATD', 'SGUAPROJ', 'TREJEICA', 'AGCOPEAT',
'SUSSPAT', 'ANACAPAE', 'AGCORCRG', 'AGCORR60', 'PAGCPART')
			AND A.STATUS_MEDIDA = 'MEDE'
		GROUP BY
			B.DISTRIBUIDORA,
			B.REGIONAL,
			B.POLO,
			B.TIPO_EQP,
			B.PROCESSO,
			REPLACE(A.EQUIPE_EXECUCAO, 'MA_', ''),
			A.MES_COMPETENCIA)T
	GROUP BY
		t.empresa,
		t.regional_prx,
		t.polo_prx,
		t.tipo_eqp,
		t.processo,
		t.equipe,
		t.competencia ) TT
LEFT JOIN 
          (
	SELECT
		n.empresa,
		n.regional_prx,
		n.polo_prx,
		n.tipo_eqp,
		n.processo,
		n.equipe,
		n.competencia,
		sum(n.qtd_dentro)qtd_dentro
	FROM
		(
		SELECT
			B.DISTRIBUIDORA EMPRESA,
			B.REGIONAL REGIONAL_PRX ,
			B.POLO POLO_PRX,
			B.TIPO_EQP TIPO_EQP,
			B.PROCESSO PROCESSO ,
			REPLACE(A.EQUIPE_EXECUCAO, 'MA_', '') EQUIPE,
			A.MES_COMPETENCIA COMPETENCIA,
			COUNT(A.NOTA) QTD_DENTRO
			--QTD_DENTRO	
			--PERC	
			--CLASSE_MEPE_PRAZO	
			--MEPE_PRAZO	
		FROM
			{{ ref('prazo_sap_stc_ma') }} A
		LEFT JOIN {{ ref('vw_gp_gstc_equipes_sem_duplicatas') }} B ON
			B.DISTRIBUIDORA = A.EMPRESA
			AND B.PREFIXO = REPLACE(REPLACE(A.EQUIPE_EXECUCAO, 'MA_', ''), 'MA_', '')
			--LEFT JOIN OWENGCMR.EQUIPES_STC_DE_PARA C ON C.EMPRESA = A.EMPRESA AND C.NOVO=REPLACE(A.EQUIPE_EXECUCAO, 'MA_', '')
		WHERE
			TO_DATE(A.MES_COMPETENCIA, 'YYYYMM') = TO_DATE({{ get_month_ref() }},'YYYYMM')
			AND A.STATUS_PRAZO = 'ATENDIDO NO PRAZO'
			AND A.STATUS_CCS NOT IN ('CANC')
				AND A.TIPO_NOTA NOT IN ('IS')
					AND A.CODIFICACAO NOT IN ('CMRE', 'LNGA', 'PLPT', 'REDF')
						AND A.GRUPO_CODES NOT IN ('ACESMNGD', 'DSPEDEMP', 'LIGEATBT', 'LIGNOVAT', 'RELIGAAT', 'RELIGARI', 'RELIGARM', 'DSBTREMO', 'DSDEFFAT', 'SATEMPAT', 'INSPCOME',
'LIGEMUC', 'LIGNOVRE', 'LNMICRGD')
							AND A.GRUPO_MEDIDA NOT IN ('AGCLPMM', 'AGPGCASP', 'AGPGCPAR', 'ANACAPAS', 'ANALIMED', 'CORRECRO', 'DISPONPI', 'ENVBOLE', 'EXECONGD', 'EXEOBRRO', 'GERABAPO',
'INFOEXPA', 'INFOGERE', 'INSPOBRD', 'INTELEDE', 'OBRAINTE', 'ORCAPTAV', 'PENDOBRA', 'PENSATD', 'SGUAPROJ', 'TREJEICA', 'AGCOPEAT',
'SUSSPAT', 'ANACAPAE', 'AGCORCRG', 'AGCORR60', 'PAGCPART')
								AND A.STATUS_MEDIDA = 'MEDE'
							GROUP BY
								B.DISTRIBUIDORA,
								B.REGIONAL,
								B.POLO,
								B.TIPO_EQP,
								B.PROCESSO,
								REPLACE(A.EQUIPE_EXECUCAO, 'MA_', ''),
								A.MES_COMPETENCIA)n
	GROUP BY
		n.empresa,
		n.regional_prx,
		n.polo_prx,
		n.tipo_eqp,
		n.processo,
		n.equipe,
		n.competencia ) NP ON
	NP.EMPRESA = TT.EMPRESA
	AND NP.EQUIPE = TT.EQUIPE
	AND NP.COMPETENCIA = TT.COMPETENCIA