Select DISTINCT 
'EQTL_PA' EMPRESA,
R.REGIONAL,
R.SECCIONAL,
CASE 
WHEN r.seccional = 'BURITICUPU' THEN 'ACAILANDIA'
WHEN r.seccional = 'COROATA' THEN 'BACABAL'
WHEN r.seccional = 'CODO' THEN 'CAXIAS'
WHEN r.seccional IN ('AMARANTE DO MARANHAO','PORTO FRANCO') THEN 'IMPERATRIZ'
WHEN r.seccional = 'MIRANDA DO NORTE' THEN 'ITAPECURU-MIRIM'
WHEN r.seccional = 'LAGO DA PEDRA' THEN 'PEDREIRAS'
WHEN r.seccional = 'CURURUPU' THEN 'PINHEIRO'
WHEN r.seccional = 'BARRA DO CORDA' THEN 'PRESIDENTE DUTRA'
WHEN r.seccional = 'ZE DOCA' THEN 	'SANTA INES'
WHEN r.seccional = 'COLINAS' THEN 'SAO JOAO DOS PATOS'
WHEN r.seccional = 'COELHO NETO' THEN 'TIMON'
ELSE r.seccional
END BASE,
R.MUNICIPIO,
R.LOCALIDADE,
N.NOTA,
N.CONTA_CONTRATO,
N.TIPO_NOTA,
N.GRUPO_CODES,
N.CODIFICACAO,
N.STATUS_CCS,
a.nr_visita,
a.grupo_medida,
a.codigo_medida,
C.DESCRICAO,
CASE 
WHEN N.TIPO_NOTA = 'LN' AND C.DESCRICAO IN ('EXECUÇÃO VISTORIA COM LIGAÇÃO','EXECUÇÃO VISTORIA COM LIGAÇÃO','EXECUTADO C/ FINANCIAMENTO DE PADRÃO','EXECUÇÃO VISTORIA C/ LIGAÇÃO E FINANCIAMENTO DO PADRÃO') AND A.NR_VISITA = '000001' THEN 'S'
WHEN N.TIPO_NOTA = 'RL' AND C.DESCRICAO IN ('SERVIÇO EXECUTADO','EXECUTADO','EXECUTADO COM FINANCIAMENTO DE PADRÃO','NAO EXECUTADO','EXECUTADO C/ FINANCIAMENTO DE PADRÃO','EXECUTADO COM TROCA/INSTALAÇÃO MD','EXECUTADO COM TROCA DE MEDIDOR',
'EXECUTADO C/ TROCA DE MEDIDOR ','EXECUTADO COM TROCA DE MEDIDOR E FINANCIAMENTO DE PADRÃO','EXEC.TROCA DE MEDIDOR E FINANC. PADRÃO','EXECUTADO-REGULARIZAÇÃO DE AUTO RELIGADO','RELIGADO SIMBOLICO','EXECUTADO COM MUDANÇA DE MEDIDOR DE LOCAL','EXECUTADO COM MUDANÇA MEDIDOR DE LOCAL',
'EXECUTADO COM MUDANÇA DE MEDIDOR DE LOCAL E FINCIAMENTO DE PADRÃO','EXEC C/ DESLOC. MEDIDOR / FINC. PADRÃO','EXECUTADO COM MUDANÇA DE RAMAL','EXECUTADO LIGADO DIRETO/SEM PADRÃO','EXECUTADO COM MUDANÇA DE RAMAL E FINCIAMENTO DE PADRÃO','EXEC.C/MUDANÇA DE RAMAL/FINANC.DE PADRÃO','EXECUTADO COM IMOVEL FECHADO','EXECUTADO C/ IMOVEL FECHADO','EXECUTADO- VERIFICAR CORTE INDEVIDO') AND A.NR_VISITA = '000001' THEN 'S'
ELSE 'N' END PRIM_VISITA,
a.equipe_execucao,
N.MES_COMPETENCIA,
N.DATA_NOTA,
N.DATA_ENCERRAMENTO,
a.data_inicio_servico,
a.data_final_servico,
a.data_inicio_deslocamento,
a.data_final_deslocamento,
C.TIPO_CONCLUSAO

 from EQTLINFO_PRD.EQTL_PA.NOTAS_SERVICOS_FECHADAS N
LEFT JOIN  EQTLINFO_PRD.EQTL_PA.visitas_notas a ON A.NOTA =N.NOTA  --and n.fim_avaria=a.data_final_servico
LEFT JOIN EQTLINFO_RAW.OPER_PA.CODE_MEDIDA C ON c.code_medida_id = a.codigo_medida and a.grupo_medida = c.grupo_code_medida_id and n.grupo_codes=c.ossubtipo_id
LEFT JOIN EQTLINFO_PRD.EQTL_PA.TAB_REGIONAL_POLITICA R ON R.ESTRUTURA_REGIONAL_POLITICA = N.ESTRUT_REGIONAL_POLITICA
 
where 

N.STATUS_CCS NOT IN ('CANC')
and N.TIPO_NOTA IN ('RL','LN')
and A.NR_VISITA = '000001'
and TRY_TO_DATE(N.MES_COMPETENCIA,'YYYYMM') = TO_DATE({{ get_month_ref() }},'YYYYMM')
AND N.GRUPO_CODES IN ('RELIGABT','LIGPROVI','LIGNOVBT','LIGREATI','LIGEATBT','LIGANOVA')
AND A.GRUPO_MEDIDA IN ('EXECSERV','EXCSERVI','VISTLGPR','EXELIGPR','EXECTRPT','VISTLGNV','EXELIGNV',
'VISLGNVN','EXLIGNOV','VISTORIA','LIGACAO')