with source as (
select
  HIST_TURMA_PLANTAO_ID,
  VIATURA_ID,
  HTP_INICIO_TURNO,
  HTP_FIM_TURNO,
  HTP_ODOMETRO_INICIO_TURNO,
  HTP_ODOMETRO_FIM_TURNO,
  HTP_SAIDA_PREVISTA,
  HTP_TELEFONE,
  HTP_OBSERVACAO,
  USUARIO_ID_INICIO,
  USUARIO_ID_FIM,
  HTP_SINCRONIZADO,
  PREFIXO_TURMA_ID,
  HTP_FIM_INTERVALO,
  HTP_INICIO_INTERVALO
  from {{ source('oper_al','historico_turma_plantao') }}
)

select * from source