version: 2

sources:
  # ========================================
  # OPER sources - Dados operacionais RAW
  # ========================================
  
  - name: OPER_AL
    database: EQTLINFO_RAW
    schema: OPER_AL
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial

  - name: OPER_AP
    database: EQTLINFO_RAW
    schema: OPER_AP
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial

  - name: OPER_GO
    database: EQTLINFO_RAW
    schema: OPER_GO
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial

  - name: OPER_MA
    database: EQTLINFO_RAW
    schema: OPER_MA
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial

  - name: OPER_PA
    database: EQTLINFO_RAW
    schema: OPER_PA
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial
  
  - name: OPER_PI
    database: EQTLINFO_RAW
    schema: OPER_PI
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial
  
  - name: OPER_RS
    database: EQTLINFO_RAW
    schema: OPER_RS
    tables:
      - name: ocorrencia
      - name: atribui_oc_emergencial
      - name: atribui_oc_mensagem_retorno
      - name: atribui_os_mensagem_retorno
      - name: tipo_de_subcausa
      - name: tipo_de_causa
      - name: historico_ocorrencia_turma
      - name: historico_turma_plantao
      - name: prefixo_turma
      - name: base
      - name: ponto_apoio
      - name: unidade_territorial
      - name: regiao_eletrica
      - name: bairro
      - name: localidade
      - name: municipio
      - name: code_medida
      - name: tipo_de_componente_danificado
      - name: instalacao_operacao
      - name: conclui_os_comercial
      - name: tipo_ocorrencia_corte
      - name: atribui_os_comercial
      - name: turma_os_comercial
      - name: movto_os_comercial

  # ========================================
  # EQTL PERFORMANCE sources
  # ========================================
  
  - name: EQTL_AL_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_AL
    tables:
      - name: tab_cod_irregularidade

  - name: EQTL_AP_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_AP
    tables:
      - name: tab_cod_irregularidade

  - name: EQTL_GO_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_GO
    tables:
      - name: tab_cod_irregularidade

  - name: EQTL_MA_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_MA
    tables:
      - name: tab_cod_irregularidade

  - name: EQTL_PA_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_PA
    tables:
      - name: tab_cod_irregularidade

  - name: EQTL_PI_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_PI
    tables:
      - name: tab_cod_irregularidade_pi

  - name: EQTL_RS_PERFORMANCE
    database: SB_PERFORMANCE
    schema: EQTL_RS
    tables:
      - name: tab_cod_irregularidade

  # ========================================
  # EQTL PRD sources
  # ========================================

  - name: EQTL_AL
    database: EQTLINFO_PRD
    schema: EQTL_AL
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_AP
    database: EQTLINFO_PRD
    schema: EQTL_AP
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_GO
    database: EQTLINFO_PRD
    schema: EQTL_GO
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_MA
    database: EQTLINFO_PRD
    schema: EQTL_MA
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_PA
    database: EQTLINFO_PRD
    schema: EQTL_PA
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_PI
    database: EQTLINFO_PRD
    schema: EQTL_PI
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  - name: EQTL_RS
    database: EQTLINFO_PRD
    schema: EQTL_RS
    tables:
      - name: notas_servicos
      - name: visitas_notas
      - name: info_gerais_notas
      - name: tab_cadastro
      - name: notas_fiscalizacao
      - name: equipa_i_notas
      - name: medidas_notas_servicos
      - name: tipo_os_local_religacao

  # ========================================
  # SIGA sources
  # ========================================

  - name: SIGA
    database: EQTLINFO_RAW
    schema: SIGA
    tables:
      - name: TB_OFSC_ACTIVITIES_RT
      - name: tb_ofsc_resources_rt


