Select DISTINCT
'EQTL_GO' EMPRESA,                               
RG.REL_DESCRICAO REGIONAL,
PA3.PAP_NOME As PONTO_APOIO,
BS.BAS_NOME BASE,
LO.LOC_NOME LOCALIDADE,
MP.MNC_NOME MUNICIPIO,
BR.BAI_NOME BAIRRO,
CASE 
WHEN IO.IOP_LOCALIZACAO IS NULL THEN DECODE(CONS.TB_CR_ID,'','URBANO','COM','URBANO','ILP','URBANO','IND','URBANO','IPP','URBANO','OUT','URBANO','PDP','URBANO','POD','URBANO','PRO','URBANO','RES','URBANO','SER','URBANO','SVP','URBANO','RUR','RURAL')
WHEN IO.IOP_LOCALIZACAO IS NULL and CONS.TB_CR_ID IS NULL then DECODE(OS.CD_TP_LOCAL_UC,'UR','URBANO','RR','RURAL','UB','URBANO','RU','RURAL')
ELSE  DECODE(IO.IOP_LOCALIZACAO,'R','RURAL','U','URBANO','','URBANO') 
END U_R,
TRUNC(OS.NR_UC, 0)::VARCHAR UC,                               
TO_NUMBER(OS.CD_MOVTO_OS_COMERCIAL)::VARCHAR OS_OPER,
TO_NUMBER(OS.NR_OS)::VARCHAR OS,
PT.PRX_DESCRICAO EQUIPE,
OS.OSTIPO_ID,
OS.SSTIPO_ID,
OS.OSSUBTIPO_ID ,
GCM.GRUPO_CODE_MEDIDA_ID,
OS.TIPO_VIATURA_CORTE MODALIDADE,  
'CR' ABRANGENCIA,
LPAD(TO_VARCHAR(LR.TB_LCRELIG_ID), 2, '0') COD_LOCAL_RELIGACAO,
LR.LCRELIG_DESCRICAO LOCAL_RELIGACAO,
CAST(REGEXP_REPLACE( CC.CD_TP_CONCLUSAO_OS,'[^0-9]','') as numeric ) COD_CONCLUSAO,
upper(TRANSLATE(CM.DESCRICAO,
'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑáàâãäéèêëíìîïóòôõöúùûüçñ',
'AAAAAEEEEIIIIOOOOOUUUUCNaaaaaeeeeiiiiooooouuuucn')) TIPO_CONCLUSAO,
CASE 
WHEN CM.TIPO_CONCLUSAO = 'R' THEN 'IMPROCEDENTE' 
ELSE 'PROCEDENTE' END PROCEDENCIA,
'N/A' MOTIVO_REJEICAO,
OS.DT_SOLICITACAO        DATA_ORIGEM, 
AC.ATROS_DATA            DATA_ATRIBUICAO,
TC.HOST_VI_DT_INI_DESLOCAMENTO INICIO_DESLOCAMENTO,
TC.HOST_VI_DT_FIM_DESLOCAMENTO FIM_DESLOCAMENTO,
TC.HOST_VI_DT_INI_SERVICO  DATA_INICIO_SERVICO,
CC.DT_CONCLUSAO   DATA_CONCLUSAO,
TO_CHAR(CC.DT_CONCLUSAO,'YYYYMM')   COMPETENCIA,
CASE WHEN OS.DT_LIMITE_EXECUCAO_OS <= '1999-12-30' THEN NULL ELSE OS.DT_LIMITE_EXECUCAO_OS END DATA_LIMITE,
CASE
    WHEN OS.DT_LIMITE_EXECUCAO_OS <= '1999-12-30' THEN NULL
    When (OS.OSTIPO_ID = 'RI' And CC.DT_CONCLUSAO > OS.DT_LIMITE_EXECUCAO_OS) Then  'FORA DO PRAZO'
    When (OS.OSTIPO_ID = 'RI' And CC.DT_CONCLUSAO < OS.DT_LIMITE_EXECUCAO_OS) Then 'DENTRO DO PRAZO'
    When (OS.OSTIPO_ID <> 'RI ' And TO_CHAR(CC.DT_CONCLUSAO, 'mm/dd/yyyy') > TO_CHAR(OS.DT_LIMITE_EXECUCAO_OS, 'mm/dd/yyyy')) Then 'FORA DO PRAZO'
    When (OS.OSTIPO_ID <> 'RI ' And TO_CHAR(CC.DT_CONCLUSAO, 'mm/dd/yyyy') <= TO_CHAR(OS.DT_LIMITE_EXECUCAO_OS, 'mm/dd/yyyy')) Then 'DENTRO DO PRAZO'
End STATUS_PRAZO,                                                         
TO_CHAR(CC.DT_CONCLUSAO, 'DD') DIA,
'SEM_' || LPAD(TO_VARCHAR(DATE_PART(weekofyear, CC.DT_CONCLUSAO)- DATE_PART(weekofyear, DATE_TRUNC('month', CC.DT_CONCLUSAO)) + 1), 2,'0') SEMANA_MES_CONC,
UPPER(TO_CHAR(CC.DT_CONCLUSAO, 'DY')) SEMANA_MES_ABREV,
TO_CHAR(CC.DT_CONCLUSAO, 'MM') As "MES_CONCL",
UPPER(TO_CHAR(CC.DT_CONCLUSAO, 'MON')) MES_CONCL_ABREV,
TO_CHAR(CC.DT_CONCLUSAO, 'YYYY') As "ANO_CONCL",
(TO_CHAR(CC.DT_CONCLUSAO, 'MM')) || '/' || (TO_CHAR(CC.DT_CONCLUSAO, 'YYYY')) As "MES_ANO",
TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') As HORA_CONCL,
CASE 
    WHEN  TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') >= '01:00:00' AND TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') < '08:00:00' THEN 'MADRUGADA'
    WHEN  TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') >= '08:00:00' AND TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') < '13:00:00' THEN 'MANHA'
    WHEN  TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') >= '13:00:00' AND TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') < '18:00:00' THEN 'TARDE'
    WHEN  TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') >= '18:00:00' AND TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') < '23:59:59' THEN 'NOITE'
    WHEN  TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') >= '00:00:00' AND TO_CHAR(CC.DT_CONCLUSAO, 'HH24:MI:SS') <= '01:00:00' THEN 'NOITE'
ELSE 'ERRO'
END TURNO,
CURRENT_TIMESTAMP DATA_DADOS
From   EQTLINFO_RAW.OPER_GO.MOVTO_OS_COMERCIAL OS 
Left Outer Join EQTLINFO_RAW.OPER_GO.BAIRRO BR                  On     BR.BAIRRO_ID = OS.CD_BAIRRO
Left Outer Join  EQTLINFO_RAW.OPER_GO.LOCALIDADE LO             On     LO.LC_ID = BR.LC_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.MUNICIPIO MP               On     to_number(MP.MNC_ID) = to_number(LO.MNC_ID)
Left Outer Join EQTLINFO_RAW.OPER_GO.CONCLUI_OS_COMERCIAL CC    On     CC.CD_MOVTO_OS_COMERCIAL = OS.CD_MOVTO_OS_COMERCIAL
Left Outer Join EQTLINFO_RAW.OPER_GO.ATRIBUI_OS_COMERCIAL AC    On     AC.CD_MOVTO_OS_COMERCIAL = OS.CD_MOVTO_OS_COMERCIAL
Left Outer Join EQTLINFO_RAW.OPER_GO.PREFIXO_TURMA PT           On     PT.PREFIXO_TURMA_ID = AC.PREFIXO_TURMA_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.TURMA_OS_COMERCIAL TC      On     TC.ATRIBUICAO_OS_ID = AC.ATRIBUICAO_OS_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.BASE BS                    On     BS.BASE_ID = BR.BASE_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.PONTO_APOIO PA             On     PA.CODIGO_PA = BS.CODIGO_PA
Left Outer Join EQTLINFO_RAW.OPER_GO.REGIAO_ELETRICA RG         On     RG.REG_ELETRICA_ID = PA.REG_ELETRICA_ID
Left Outer Join EQTLINFO_PRD.EQTL_GO.TIPO_OS_LOCAL_RELIGACAO LR On     LR.TB_LCRELIG_ID = CC.CD_LOCAL_RELIGACAO
Left Outer Join EQTLINFO_RAW.OPER_GO.BASE BS3                   On     BS3.BASE_ID = MP.BASE_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.PONTO_APOIO PA3            On     PA3.CODIGO_PA = BS.CODIGO_PA
Left Outer Join EQTLINFO_RAW.OPER_GO.CODE_MEDIDA CM             On     CM.OSSUBTIPO_ID = OS.OSSUBTIPO_ID And CM.GRUPO_CODE_MEDIDA_ID = OS.GRUPO_CODE_MEDIDA_ID   And CM.CODE_MEDIDA_ID = CC.CD_TP_CONCLUSAO_OS
Left Outer Join EQTLINFO_RAW.EQTL_GO.GRUPO_CODE_MEDIDA GCM      On     GCM.GRUPO_CODE_MEDIDA_ID = CM.GRUPO_CODE_MEDIDA_ID            And GCM.OSSUBTIPO_ID = OS.OSSUBTIPO_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.CONSUMIDOR CONS               On     CONS.CR_NUMERO = OS.NR_UC
Left Outer Join EQTLINFO_RAW.OPER_GO.CONCLUI_COMPLEMENTO_INSPECAO IC on   IC.CD_MOVTO_OS_COMERCIAL = OS.CD_MOVTO_OS_COMERCIAL AND CC.HIST_OS_TURMA_ID = IC.HIST_OS_TURMA_ID
Left Outer Join EQTLINFO_RAW.OPER_GO.TIPO_OCORRENCIA_CORTE OC   On     OC.TPOCO_CORTE_ID = IC.TPOCO_CORTE_ID
Left   Join EQTLINFO_RAW.OPER_GO.INSTALACAO_OPERACAO IO ON IO.INSTALACAO_ID = OS.NR_UC
INNER join (Select CD_MOVTO_OS_COMERCIAL, Max(ATRIBUICAO_OS_ID) as ATRIBUICAO_OS_ID
            From   EQTLINFO_RAW.OPER_GO.ATRIBUI_OS_COMERCIAL AC2
            Group  By AC2.CD_MOVTO_OS_COMERCIAL) AC2
On AC2.CD_MOVTO_OS_COMERCIAL = AC.CD_MOVTO_OS_COMERCIAL 
AND AC2.ATRIBUICAO_OS_ID = AC.ATRIBUICAO_OS_ID 
Where TRUNC(CC.DT_CONCLUSAO, 'YYYY') = '2025-01-01'

UNION ALL

SELECT
	DISTINCT 
                         'EQTL_GO' EMPRESA,
	RG.REL_DESCRICAO REGIONAL,
	PA3.PAP_NOME PONTO_APOIO,
	BS.BAS_NOME BASE,
	LO.LOC_NOME LOCALIDADE,
	MP.MNC_NOME MUNICIPIO,
	BR.BAI_NOME BAIRRO,
	CASE
		WHEN IO.IOP_LOCALIZACAO IS NULL THEN DECODE(CONS.TB_CR_ID, '', 'URBANO', 'COM', 'URBANO', 'ILP', 'URBANO', 'IND', 'URBANO', 'IPP', 'URBANO', 'OUT', 'URBANO', 'PDP', 'URBANO', 'POD', 'URBANO', 'PRO', 'URBANO', 'RES', 'URBANO', 'SER', 'URBANO', 'SVP', 'URBANO', 'RUR', 'RURAL')
		ELSE DECODE(IO.IOP_LOCALIZACAO, 'R', 'RURAL', 'U', 'URBANO', '', 'URBANO')
	END U_R,
	CASE
		WHEN TRUNC(OC.CR_NUMERO, 0) IS NULL THEN OC.INSTALACAO_ID
	END::INTEGER::VARCHAR UC,
	OC.OCORRENCIA_ID::INTEGER::VARCHAR OS_OPER,
	OC.OCO_NUMERO::INTEGER::VARCHAR OS,
	PT.PRX_DESCRICAO EQUIPE,
	'NR' OSTIPO_ID,
	'NR' sstipo_id,
	CASE
		WHEN OC.TB_TP_ABRANGENCIA = 'CR' THEN 'IND'
		WHEN OC.TB_TP_ABRANGENCIA = 'NI' THEN 'IND'
		ELSE 'COL'
	END OSSUBTIPO_ID,
	T.GRUPO_CODE_MEDIDA_ID,
	NULL MODALIDADE,
	OC.TB_TP_ABRANGENCIA ABRANGENCIA,
	NULL COD_LOCAL_RELIGACAO,
	NULL LOCAL_RELIGACAO,
	CAST(REGEXP_REPLACE( to_number(OC.TB_CAUSA_ID),'[^0-9]','') as numeric ) COD_CONCLUSAO,
	upper(TRANSLATE(TC.TCA_DESCRICAO,
                           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑáàâãäéèêëíìîïóòôõöúùûüçñ',
                           'AAAAAEEEEIIIIOOOOOUUUUCNaaaaaeeeeiiiiooooouuuucn')) TIPO_CONCLUSAO,
	CASE
		WHEN OC.TB_CAUSA_ID IN (11, 14, 22, 23, 34, 39, 56, 82, 83, 84, 85) THEN 'IMPROCEDENTE'
		ELSE 'PROCEDENTE'
	END PROCEDENCIA,
	/* 11 TRANSFORMADOR NORMAL- CONFERIDO RECLAMACAO
14 INSTALA O AP S MEDI O COM DEFEITO - CLIENTE
22 DISJUNTOR MT GRUPO A- DESARMADO
23 DISJUNTOR BT - CLIENTE DESARMADO
34 REDE TELEF NICA / TV A CABO
39 ENCONTRADO ENERGIA CORTADA - CLIENTE
56 ENDERECO NAO LOCALIZADO
82 ILUMINA AO PUBLICA COM DEFEITO
83 PORTEIRA TRANCADA
84 ACESSO IMPEDIDO
85 ENCONTRADO NORMAL - UC */
                               NULL MOTIVO_REJEICAO,
	OC.OCO_DATA_NR DATA_ORIGEM,
	OC.OCO_DATA_ACIONAMENTO DATA_ATRIBUICAO,
	OT.HOT_VI_DATA_ACEITE INICIO_DESLOCAMENTO,
	OT.HOT_VI_DATA_CHEGADA FIM_DESLOCAMENTO,
	ot.hot_vi_data_chegada DATA_INICIO_SERVICO,
	OC.OCO_DATA_CONCLUSAO DATA_CONCLUSAO,
	TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'YYYYMM') COMPETENCIA,
	OC.OCO_HORA_PREVISTA DATA_LIMITE,
	CASE
		WHEN OT.HOT_VI_DATA_CONCLUSAO <= OC.OCO_HORA_PREVISTA THEN 'DENTRO DO PRAZO'
		ELSE 'FORA DO PRAZO'
	END STATUS_PRAZO,
	TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'DD') DIA,
	'SEM_' || LPAD(TO_VARCHAR(DATE_PART(weekofyear, OC.OCO_DATA_CONCLUSAO)- DATE_PART(weekofyear, DATE_TRUNC('month', OC.OCO_DATA_CONCLUSAO)) + 1), 2,'0') SEMANA_MES_CONC,
	UPPER(TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'DY')) SEMANA_MES_ABREV,
	TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'MM') AS "MES_CONCL",
	UPPER(TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'MON')) MES_CONCL_ABREV,
	TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'YYYY') AS "ANO_CONCL",
	(TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'MM')) || '/' || (TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'YYYY')) AS "MES_ANO",
	TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') AS HORA_CONCL,
	CASE
		WHEN TO_CHAR(OC.OCO_DATA_CONCLUSAO , 'HH24:MI:SS') >= '01:00:00'
		AND TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') < '08:00:00' THEN 'MADRUGADA'
		WHEN TO_CHAR(OC.OCO_DATA_CONCLUSAO , 'HH24:MI:SS') >= '08:00:00'
		AND TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') < '13:00:00' THEN 'MANHA'
		WHEN TO_CHAR(OC.OCO_DATA_CONCLUSAO , 'HH24:MI:SS') >= '13:00:00'
		AND TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') < '18:00:00' THEN 'TARDE'
		WHEN TO_CHAR(OC.OCO_DATA_CONCLUSAO , 'HH24:MI:SS') >= '18:00:00'
		AND TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') <= '23:59:59' THEN 'NOITE'
		WHEN TO_CHAR(OC.OCO_DATA_CONCLUSAO , 'HH24:MI:SS') >= '00:00:00'
		AND TO_CHAR(OC.OCO_DATA_CONCLUSAO, 'HH24:MI:SS') <= '01:00:00' THEN 'NOITE'
		ELSE 'ERRO'
	END TURNO,
	CURRENT_TIMESTAMP DATA_DADOS
FROM
	EQTLINFO_RAW.OPER_GO.OCORRENCIA OC
LEFT JOIN EQTLINFO_RAW.OPER_GO.TIPO_DE_CAUSA TC ON
	TC.TB_CAUSA_ID = OC.TB_CAUSA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.HISTORICO_OCORRENCIA_TURMA OT ON
	OT.OCORRENCIA_ID = OC.OCORRENCIA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.HISTORICO_TURMA_PLANTAO TP ON
	TP.HIST_TURMA_PLANTAO_ID = OT.HIST_TURMA_PLANTAO_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.PREFIXO_TURMA PT ON
	PT.PREFIXO_TURMA_ID = TP.PREFIXO_TURMA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.BASE BS ON
	BS.BASE_ID = OC.BASE_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.PONTO_APOIO PA ON
	PA.CODIGO_PA = BS.CODIGO_PA
LEFT JOIN EQTLINFO_RAW.OPER_GO.UNIDADE_TERRITORIAL UT ON
	UT.REG_ELETRICA_ID = PA.REG_ELETRICA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.REGIAO_ELETRICA RG ON
	RG.REG_ELETRICA_ID = PA.REG_ELETRICA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.BAIRRO BR ON
	BR.BAIRRO_ID = OC.BAIRRO_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.LOCALIDADE LO ON
	LO.LC_ID = BR.LC_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.MUNICIPIO MP ON
	to_char(MP.MNC_ID) = LO.MNC_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.BASE BS3 ON
	BS3.BASE_ID = MP.BASE_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.PONTO_APOIO PA3 ON
	PA3.CODIGO_PA = BS.CODIGO_PA
LEFT JOIN EQTLINFO_RAW.OPER_GO.INSTALACAO_OPERACAO IO ON
	IO.INSTALACAO_ID = OC.INSTALACAO_ID
LEFT OUTER JOIN EQTLINFO_RAW.OPER_GO.CONSUMIDOR CONS ON
	CONS.CR_NUMERO = oc.cr_numero
LEFT JOIN EQTLINFO_RAW.OPER_GO.CODE_MEDIDA T ON
	T.CDM_ID = OC.TIPO_CONCLUSAO
WHERE
	OC.OCO_STATUS = 'F'
	--and  OC.OCO_NUMERO = '35493'
	AND OT.HOT_VI_STATUS = 4
	AND TRUNC(OC.OCO_DATA_CONCLUSAO, 'YYYY') = '2025-01-01'

UNION ALL

SELECT
'EQTL_GO' EMPRESA,                               
RG.REL_DESCRICAO REGIONAL,
PA.PAP_NOME PONTO_APOIO,
BASE.BAS_NOME BASE,
LOC.LOC_NOME LOCALIDADE,
MUN.MNC_NOME MUNICIPIO,
BAI.BAI_NOME BAIRRO,
'' U_R,
--LOCALIZAR
TRUNC(MVMSC.CR_NUMERO , 0)::INTEGER::VARCHAR UC,
TO_NUMBER(MVMSC.CD_MOVTO_OS_MISCELANEA)::INTEGER::VARCHAR OS_OPER, 
(MVMSC.MSC_NUMERO)::INTEGER::VARCHAR OS,
--CONC.HIST_MSC_TURMA_ID,
PT.PRX_DESCRICAO EQUIPE,
'MT' OSTIPO_ID,
'MT' SSTIPO_ID, 
mtv.TB_MT_MISCELANEA_DESCRICAO OSSUBTIPO_ID ,
'' GRUPO_CODE_MEDIDA_ID, 
'' MODALIDADE,  
'CR' ABRANGENCIA, 
'' COD_LOCAL_RELIGACAO,
'' LOCAL_RELIGACAO,
CASE
	WHEN sm.QTD IS NULL
	OR sm.QTD = 0 THEN 2
	ELSE 1
END COD_CONCLUSAO,
CASE
	WHEN sm.QTD IS NULL
	OR sm.QTD = 0 THEN 'SERVICO NAO EXECUTADO'
	ELSE 'SERVICO EXECUTADO'
END TIPO_CONCLUSAO,
-- sm.QTD,
'N/A' PROCEDENCIA,
'' MOTIVO_REJEICAO,
ATR.ATRMS_DATA DATA_ORIGEM, 
ATR.ATRMS_DATA DATA_ATRIBUICAO,
TURM.HOST_VI_DT_INI_DESLOCAMENTO INICIO_DESLOCAMENTO,
TURM.HOST_VI_DT_CHEGADA_LOCAL FIM_DESLOCAMENTO,
TURM.HOST_VI_DT_CHEGADA_LOCAL DATA_INICIO_SERVICO,
CONC.DT_CONCLUSAO DATA_CONCLUSAO,
TO_CHAR(CONC.DT_CONCLUSAO , 'YYYYMM') COMPETENCIA,
CONC.DT_CONCLUSAO DATA_LIMITE,
'DENTRO DO PRAZO' STATUS_PRAZO,                       
TO_CHAR(CONC.DT_CONCLUSAO , 'DD') DIA,
'SEM_' || LPAD(TO_VARCHAR(DATE_PART(weekofyear, CONC.DT_CONCLUSAO)- DATE_PART(weekofyear, DATE_TRUNC('month', CONC.DT_CONCLUSAO)) + 1), 2,'0') SEMANA_MES_CONC,
UPPER(TO_CHAR(CONC.DT_CONCLUSAO , 'DY')) SEMANA_MES_ABREV,
TO_CHAR(CONC.DT_CONCLUSAO , 'MM') AS "MES_CONCL",
UPPER(TO_CHAR(CONC.DT_CONCLUSAO , 'MON')) MES_CONCL_ABREV,
TO_CHAR(CONC.DT_CONCLUSAO , 'YYYY') AS "ANO_CONCL",
(TO_CHAR(CONC.DT_CONCLUSAO , 'MM')) || '/' || (TO_CHAR(MVMSC.DT_FIM , 'YYYY')) AS "MES_ANO",
TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') AS HORA_CONCL,
CASE
	WHEN TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') >= '01:00:00'
	AND TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') < '08:00:00' THEN 'MADRUGADA'
	WHEN TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') >= '08:00:00'
	AND TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') < '13:00:00' THEN 'MANHA'
	WHEN TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') >= '13:00:00'
	AND TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') < '18:00:00' THEN 'TARDE'
	WHEN TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') >= '18:00:00'
	AND TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') < '23:59:59' THEN 'NOITE'
	WHEN TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') >= '00:00:00'
	AND TO_CHAR(CONC.DT_CONCLUSAO , 'HH24:MI:SS') <= '01:00:00' THEN 'NOITE'
	ELSE 'ERRO'
END TURNO,
CURRENT_TIMESTAMP DATA_DADOS
FROM
EQTLINFO_RAW.OPER_GO.MOVTO_OS_MISCELANEA MVMSC
LEFT JOIN EQTLINFO_RAW.OPER_GO.MOTIVO_DA_MISCELANEA MTV ON
MTV.TB_MT_MISCELANEA_ID = MVMSC.TB_MT_MISCELANEA_ID
-----------------------------ATRIBUI  ES E VISITAS------------------------------    
LEFT JOIN EQTLINFO_RAW.OPER_GO.ATRIBUI_OS_MISCELANEA ATR ON
ATR.CD_MOVTO_OS_MISCELANEA = MVMSC.CD_MOVTO_OS_MISCELANEA
-- HIST RICO DE ATRIBUI  ES
LEFT JOIN EQTLINFO_RAW.OPER_GO.TURMA_OS_MISCELANEA TURM ON
TURM.ATRIBUICAO_MSC_ID = ATR.ATRIBUICAO_MSC_ID
-- HIST RICO DE ATENDIMENTOS
INNER JOIN EQTLINFO_RAW.OPER_GO.CONCLUI_OS_MISCELANEA CONC ON
CONC.HIST_MSC_TURMA_ID = TURM.HIST_MSC_TURMA_ID
-- DADOS DA CONCLUS O RELACIONADA AO ATENDIMENTO
----------------------------EQUIPES E FORNECEDOR------------------------------
LEFT JOIN EQTLINFO_RAW.OPER_GO.PREFIXO_TURMA PT ON
PT.PREFIXO_TURMA_ID = ATR.PREFIXO_TURMA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.EMPREITEIRA EMP ON
EMP.EMPREITEIRA_ID = PT.EMPREITEIRA_ID
--LEFT JOIN EQTLINFO_RAW.OPER_GO.TIPO_EQUIPE TEQ ON TEQ.TB_EQUIPE_ID = PRX.TB_EQUIPE_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.HISTORICO_TURMA_PLANTAO HTP ON
HTP.HIST_TURMA_PLANTAO_ID = ATR.TURMA_PLANTAO_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.VIATURA VIA ON
TRIM(VIA.VIATURA_ID) = HTP.VIATURA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.TIPO_VIATURA TPV ON
TPV.VIA_TIPO_VIATURA = VIA.VIA_TIPO_VIATURA
----------------------------ENDERE O E LOCALIZA  O------------------------------
LEFT JOIN EQTLINFO_RAW.OPER_GO.BAIRRO BAI ON
MVMSC.BAIRRO_ID = BAI.BAIRRO_ID
-- TABELA CADASTRO DE BAIRROS 
LEFT JOIN EQTLINFO_RAW.OPER_GO.BASE BASE ON
BAI.BASE_ID = BASE.BASE_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.PONTO_APOIO PA ON
PA.CODIGO_PA = BASE.CODIGO_PA
LEFT JOIN EQTLINFO_RAW.OPER_GO.REGIAO_ELETRICA RG ON
RG.REG_ELETRICA_ID = PA.REG_ELETRICA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.UNIDADE_TERRITORIAL UT ON
PA.REG_ELETRICA_ID = UT.REG_ELETRICA_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.LOCALIDADE LOC ON
LOC.LC_ID = BAI.LC_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.MUNICIPIO MUN ON
to_char(MUN.MNC_ID) = LOC.MNC_ID
--------------------------------------------------------------------------------    
LEFT JOIN EQTLINFO_RAW.OPER_GO.CODE_MEDIDA CDM ON
CDM.CDM_ID = CONC.CDM_ID
-- INFORMA  O N O EST  CORRETA
LEFT JOIN EQTLINFO_RAW.OPER_GO.TIPO_DE_COMPONENTE_DANIFICADO DEF ON
DEF.TB_DEFEITO_ID = CONC.TB_DEFEITO_ID
LEFT JOIN EQTLINFO_RAW.OPER_GO.TIPO_DE_CAUSA CAUSA ON
CAUSA.TB_CAUSA_ID = CONC.TB_CAUSA_ID
LEFT JOIN (
SELECT
	S.HIST_MSC_TURMA_ID,
	SUM(S.SERV_EX_QUANTIDADE) QTD
FROM
	EQTLINFO_PRD.EQTL_GO.SERVICO_EXECUTADO_MSC S -- SUBSTITUIR POR TABELA DA GOVERNANÇA PIZZANI, 05/09/25 -- SUBSTITUIDO, 06/10/2025
GROUP BY
	S.HIST_MSC_TURMA_ID) sm ON
SM.HIST_MSC_TURMA_ID = CONC.HIST_MSC_TURMA_ID
WHERE
1 = 1
--AND TEQ.TB_EQUIPE_ID <> 'F' -- RETIRA EQUIPE VIRTUAL
AND MVMSC.STATUS_OS NOT IN ('A', 'B', 'T', 'E')
-- RETIRA OS ABERTAS
AND TRUNC(CONC.DT_CONCLUSAO, 'YYYY') >= '2025-01-01' AND TRUNC(CONC.DT_CONCLUSAO, 'YYYY') = '2026-01-01'
