SELECT
	T.*,
	B.CH_UPS,
	U.TME,
	U.TMD,
	U.TMA,
	U.UPS,
	P.REGIONAL P_REGIONAL,
	P.POLO P_POLO,
	P.FONECEDOR P_FORNECEDOR,
	P.TIPO_EQP,
	P.PROCESSO P_PROCESSO,
	P.SERV_CAMPO,
	P.QTD_ELETRICISTAS,
	P.STATUS,
	DT.QTD_TOT QTD_DIAS_TOTAIS,
	DU.QTD_UTIL QTD_DIAS_UTEIS,
	CASE
		WHEN P.SERV_CAMPO LIKE '%24%' THEN '3'
		WHEN P.SERV_CAMPO LIKE '%16%' THEN '2'
		ELSE '1'
	END TURNOS,
	CASE
		WHEN SERV_CAMPO LIKE '%3E%' THEN DT.QTD_TOT
		WHEN SERV_CAMPO LIKE '%5E%' THEN DT.QTD_TOT
		ELSE DU.QTD_UTIL
	END DIAS,
	CURRENT_TIMESTAMP DATA_DADOS
FROM
	(
	SELECT
		A.EMPRESA,
		A.REGIONAL,
		A.PONTO_APOIO,
		A.BASE,
		A.BAIRRO,
		A.LOCALIDADE,
		A.MUNICIPIO,
		A.U_R,
		A.UC,
		A.OS_OPER,
		A.OS,
		A.EQUIPE,
		A.OSTIPO_ID,
		A.SSTIPO_ID,
		A.OSSUBTIPO_ID,
		A.GRUPO_CODE_MEDIDA_ID,
		A.MODALIDADE,
		A.ABRANGENCIA,
		A.COD_LOCAL_RELIGACAO,
		A.LOCAL_RELIGACAO,
		A.COD_CONCLUSAO,
		A.TIPO_CONCLUSAO,
		A.PROCEDENCIA,
		A.MOTIVO_REJEICAO,
		A.DATA_ORIGEM,
		A.DATA_ATRIBUICAO,
		A.INICIO_DESLOCAMENTO,
		A.FIM_DESLOCAMENTO,
		A.DATA_INICIO_SERVICO,
		A.DATA_CONCLUSAO,
		A.COMPETENCIA,
		A.DATA_LIMITE,
		A.STATUS_PRAZO,
		A.DIA,
		A.SEMANA_MES_CONC,
		A.SEMANA_MES_ABREV,
		A.MES_CONCL,
		A.MES_CONCL_ABREV,
		A.ANO_CONCL,
		A.MES_ANO,
		A.HORA_CONCL,
		A.TURNO,
		CASE
    WHEN A.OSTIPO_ID = 'NR' THEN 
        NVL(A.OSTIPO_ID,'') || LTRIM(NVL(A.COD_CONCLUSAO::VARCHAR,''), '0') || NVL(A.TIPO_CONCLUSAO,'') || NVL(A.ABRANGENCIA,'')
    WHEN A.OSTIPO_ID IN ('RI', 'RL') THEN 
        NVL(A.OSTIPO_ID,'') || NVL(A.GRUPO_CODE_MEDIDA_ID,'') || LTRIM(NVL(A.COD_CONCLUSAO::VARCHAR,''), '0') || NVL(A.TIPO_CONCLUSAO,'') || NVL(A.LOCAL_RELIGACAO,'')
    WHEN A.OSTIPO_ID = 'MT' THEN 
        NVL(A.OSTIPO_ID,'') || NVL(A.OSSUBTIPO_ID,'') || LTRIM(NVL(A.COD_CONCLUSAO::VARCHAR,''), '0') || NVL(A.TIPO_CONCLUSAO,'')  
    WHEN A.OSTIPO_ID NOT IN ('NR', 'RI', 'RL') THEN 
        NVL(A.OSTIPO_ID,'') || NVL(A.GRUPO_CODE_MEDIDA_ID,'') || LTRIM(NVL(A.COD_CONCLUSAO::VARCHAR,''), '0') || NVL(A.TIPO_CONCLUSAO,'')
    ELSE 'ERRO'
END AS CHAVE_UPS
	FROM
		{{ ref('serv_exec_detalhado_2025_revisao') }} A
	
        ) T
LEFT JOIN (
	SELECT
		BB.*,
		CASE
		WHEN BB.OSTIPO_ID = 'NR' THEN 
			NVL(TO_VARCHAR(BB.OSTIPO_ID),'') 
			|| NVL(TO_VARCHAR(BB.CODE_MEDIDA_ID),'') 
			|| NVL(TO_VARCHAR(BB.TIPO_CONCLUSAO),'') 
			|| NVL(TO_VARCHAR(BB.ABRANGENCIA),'')
	
		WHEN BB.OSTIPO_ID IN ('RI', 'RL') THEN 
			NVL(TO_VARCHAR(BB.OSTIPO_ID),'') 
			|| NVL(TO_VARCHAR(BB.GRUPO_CODE_MEDIDA_ID),'') 
			|| NVL(TO_VARCHAR(BB.CODE_MEDIDA_ID),'') 
			|| NVL(TO_VARCHAR(BB.TIPO_CONCLUSAO),'') 
			|| NVL(TO_VARCHAR(BB.LOCAL_RELIGA),'')
	
		WHEN BB.OSTIPO_ID NOT IN ('NR', 'RI', 'RL') THEN 
			NVL(TO_VARCHAR(BB.OSTIPO_ID),'') 
			|| NVL(TO_VARCHAR(BB.GRUPO_CODE_MEDIDA_ID),'') 
			|| NVL(TO_VARCHAR(BB.CODE_MEDIDA_ID),'') 
			|| NVL(TO_VARCHAR(BB.TIPO_CONCLUSAO),'')
	
		ELSE 'ERRO'
	END AS CHAVE_UPS
	FROM
		SB_PERFORMANCE.EQTL_CORP.UPS_CONVERSAO_CODES BB ) B ON
	B.CHAVE_UPS = T.CHAVE_UPS
LEFT JOIN (
	
	SELECT * FROM SB_PERFORMANCE.EQTL_CORP.GP_GSTC_EQUIPES2021_BACKUP 
	
	) P ON
	P.DISTRIBUIDORA = T.EMPRESA
	AND P.PREFIXO = T.EQUIPE
	AND T.DATA_CONCLUSAO >= P.VIGENCIA_INICIAL_EQP
	AND T.DATA_CONCLUSAO <= P.VIGENCIA_FINAL_EQP
LEFT JOIN {{ ref('tab_ups_2025_revisao') }} U ON
	U.CHAVE_UPS = T.EMPRESA || P.REGIONAL || P.POLO || P.PROCESSO || B.CH_UPS
LEFT JOIN (
	SELECT
		count(d2.data) QTD_TOT,
		d2.competencia2,
		d2.ano
	FROM
		(
		SELECT
			d1.data,
			d1.dia_semana,
			d1.ano,
			d1.cod_mes,
			d1.competencia2,
			CASE
				WHEN df.data IS NOT NULL THEN 'SIM'
				ELSE 'NÃO'
			END FERIADO
		FROM
			SB_PERFORMANCE.EQTL_CORP.dias_trabalho d1
		LEFT JOIN (
			SELECT
				DISTINCT A.DATA
			FROM
				SB_PERFORMANCE.EQTL_CORP.tab_feriados_ccs a
			WHERE
				a.ano_calc_feriado > '2010'
				AND a.id_cal_feriado = 'AA'
				AND a.regra_feriado IS NULL
				AND a.municipio IS NULL
				AND a.data < CURRENT_TIMESTAMP ) df ON
			df.data = d1.data) d2
	WHERE
		D2.DATA<CURRENT_TIMESTAMP
	GROUP BY
		d2.competencia2,
		d2.ano /* DIAS TOTAIS */ ) DT ON
	DT.COMPETENCIA2 = T.COMPETENCIA
LEFT JOIN (
	SELECT
		count(d2.data) QTD_UTIL,
		d2.competencia2,
		d2.ano
	FROM
		(
		SELECT
			d1.data,
			d1.dia_semana,
			d1.ano,
			d1.cod_mes,
			d1.competencia2,
			CASE
				WHEN df.data IS NOT NULL THEN 'SIM'
				ELSE 'NÃO'
			END FERIADO
		FROM
			SB_PERFORMANCE.EQTL_CORP.dias_trabalho d1
		LEFT JOIN (
			SELECT
				DISTINCT A.DATA
			FROM
				SB_PERFORMANCE.EQTL_CORP.tab_feriados_ccs a
			WHERE
				a.ano_calc_feriado > '2010'
				AND a.id_cal_feriado = 'AA'
				AND a.regra_feriado IS NULL
				AND a.municipio IS NULL
				AND a.data < CURRENT_TIMESTAMP ) df ON
			df.data = d1.data
		WHERE
			DF.DATA IS NULL
			AND d1.dia_semana NOT IN ('SABADO ', 'DOMINGO')
				AND d1.DATA < CURRENT_TIMESTAMP ) d2
	GROUP BY
		d2.competencia2,
		d2.ano /* DIAS UTEIS */ ) DU ON
	DU.COMPETENCIA2 = T.COMPETENCIA