SELECT 
A.EMPRESA,	
A.REGIONAL_PRX,	
A.POLO_PRX,
A.FORNECEDOR,	
A.EQUIPE,
A.PROCESSO_PRX,	
A.TIPO_EQP,	
A.SERV_CAMPO,	
A.MES_CONCL,
A.MES_ANO,	
A.ANO_CONCL,	
A.COMPETENCIA,	
SUM(A.RESULTADO_UPS) REALIZADO_MENSAL,	
(A.DIAS*42*A.TURNOS) META_MENSAL,	
A.DIAS DIAS_UTEIS,	
A.TURNOS,
((SUM(A.RESULTADO_UPS)/A.DIAS)/A.TURNOS) MEDIA_UPS_MES,	
(SUM(A.RESULTADO_UPS)/(A.DIAS*42*A.TURNOS)) ADERENCIA_META,	
CASE 
WHEN ((SUM(A.RESULTADO_UPS)/(A.DIAS*42*A.TURNOS))*100) >  90 THEN 'A'
WHEN ((SUM(A.RESULTADO_UPS)/(A.DIAS*42*A.TURNOS))*100) >  75 THEN 'B'
WHEN ((SUM(A.RESULTADO_UPS)/(A.DIAS*42*A.TURNOS))*100) >  40 THEN 'C'
WHEN ((SUM(A.RESULTADO_UPS)/(A.DIAS*42*A.TURNOS))*100) <= 40 THEN 'D'
ELSE '' END  CLASSE_MEPE_UPS,
CURRENT_TIMESTAMP DATA_DADOS
from {{ ref('ups_diario_2025_revisao') }} A
where 1 = 1
GROUP BY 
A.EMPRESA,	
A.REGIONAL_PRX,	
A.POLO_PRX,
A.FORNECEDOR,	
A.EQUIPE,
A.PROCESSO_PRX,	
A.TIPO_EQP,	
A.SERV_CAMPO,	
A.MES_CONCL,
A.MES_ANO,	
A.ANO_CONCL,	
A.COMPETENCIA,	
A.DIAS,	
A.TURNOS